### ISSUE TITLE
No need for experimental gate for HashMap

### ISSUE THREAD

**Issue by Ms2ger** [servo/heapsize#28]
`hashmap_build_hasher` seems to be stable now.

**Comment by SimonSapin** [comment]
It’s `#[stable]` since 1.7.0. Let’s do this when that reaches the stable channel.

**Comment by nox** [comment]
We should take this opportunity to make a breaking change and add a `B: HeapSizeOf` for the hash builder.

**Comment by nox** [comment]
This was done AFAIK.
