### ISSUE TITLE
Consider relicensing

### ISSUE THREAD

**Issue by Ms2ger** [servo/heapsize#31]
CC @larsbergstrom @metajack 

We might eventually want this to end up in the standard library, which I believe (IANAL) means it needs to be Apache/MIT rather than MPL2.

**Comment by larsbergstrom** [comment]
I'm fine with relicensing this as Apache/MIT.

**Comment by metajack** [comment]
I'm also fine with relicensing.

**Comment by Ms2ger** [comment]
People who touched this repository:
- Anthony Ramine
- bors-servo
- bors-servo
- Emilio Cobos Álvarez
- Jack Moffitt
- Josh Matthews
- Manish Goregaokar
- Michael Howell
- Ms2ger
- Pyfisch
- Simon Sapin

People who touched components/util/memory.rs:
- Alan Jeffrey
- Aleksandr Likhanov
- Anthony Ramine
- Bobby Holley
- Bogdan Cuza
- Brandon Fairchild
- Corey Farwell
- ecoal95
- Glenn Watson
- Johann Tuffe
- Josh Matthews
- Manish Goregaokar
- Ms2ger
- Nicholas Nethercote
- Patrick Walton
- Ravi Shankar
- Simon Sapin

People who touched components/util/memory.rs after ece2711185cffa8ade21b0ab9538bc1be79cadb9
- Matt Brubeck
- Ms2ger
- Nicholas Nethercote
- Simon Sapin

**Comment by ecoal95** [comment]
I'm fine with it :)

**Comment by Manishearth** [comment]
I'm also fine with it.

**Comment by nnethercote** [comment]
Ok by me.

**Comment by glennw** [comment]
I'm also fine with relicensing.

**Comment by asajeffrey** [comment]
Me too.

**Comment by jdm** [comment]
Agreed.

**Comment by SimonSapin** [comment]
Sounds good.

**Comment by frewsxcv** [comment]
Do whatever you want my contributions.

**Comment by mbrubeck** [comment]
I agree.

**Comment by nox** [comment]
Fine.

**Comment by brson** [comment]
What's the status here? Can somebody move this across the finish line? It's a dep of some really important crates, like URL.

**Comment by mbrubeck** [comment]
I converted the list above to a checklist and checked off people who have approved relicensing in the comments here.  We should ping anyone remaining who holds copyright over any code that's currently in this repo.  (Code produced by someone in their capacity as a Mozilla employee might needs Mozilla approval rather than the author's approval; check with the licensing experts to be sure.)

**Comment by Wafflespeanut** [comment]
Sorry I missed this somehow. It's fine by me.

**Comment by Wafflespeanut** [comment]
cc'ing @pcwalton @notriddle @bholley @pyfisch

**Comment by bholley** [comment]
Fine by me.

**Comment by notriddle** [comment]
☑️ Michael Howell

**Comment by pyfisch** [comment]
Fine by me.

**Comment by emilio** [comment]
@boghison, are you fine with this?

**Comment by emilio** [comment]
Also @nerith, would you be fine with this relicensing?

 * Aleksandr Likhanov doesn't appear to have touched components/util/mem.rs, I only see two commits by him: https://github.com/servo/servo/commit/d891e75d9d51a4349c5e15af0d99b4a2cb7c8ac7, and https://github.com/servo/servo/commit/4bf21ab15e9adb0b1dd8c4d3993d6d3ea4c1c6a3.
 * Jonnathan Tuffe only has https://github.com/servo/servo/commit/dd1c8c826edcd54caa4d863aa2aa0e21fece5dbc, https://github.com/servo/servo/commit/009f6f63ad45164b7ef7fbc6322d421143c03185 and https://github.com/servo/servo/commit/ec07178b6fc5a0ab559eb191952101cf92b5d666, none of them seem to touch anything related to this crate.

So without those, only @Ms2ger (which I assume should be checked? he proposed this) and @pcwalton remain.

**Comment by boghison** [comment]
Ok.

**Comment by brson** [comment]
So close...

**Comment by nerith** [comment]
I'm fine with this.

**Comment by Manishearth** [comment]
@Ms2ger thoughts?

**Comment by wafflespeanut** [comment]
Also pinging @tafia and @vegayours

**Comment by vegayours** [comment]
If this matters, I'm fine with this.

**Comment by tafia** [comment]
Fine for me too!

**Comment by Ms2ger** [comment]
Fine by me.

**Comment by pcwalton** [comment]
Ack.

**Comment by metajack** [comment]
And we're done with permission seeking. Now we just need someone to update the license in code and docs.

**Comment by brson** [comment]
Thanks a bunch everyone!
