### ISSUE TITLE
Implement heapsize for other libraries

### ISSUE THREAD

**Issue by notriddle** [servo/heapsize#4]
Should the rust-url `HeapSizeOf` go here, or in rust-url? It can go in either place, but trait coherence rules won't let it go into a third crate (like staying in `components/util`)

**Comment by jdm** [comment]
I'm inclined to add implementations to the original libraries, with a [Cargo feature](http://doc.crates.io/manifest.html#the-[features]-section) so only the people who want the functionality must pay for it.

**Comment by notriddle** [comment]
That's what I figured
