### ISSUE TITLE
Implement heap size support on Windows

### ISSUE THREAD

**Issue by saneyuki** [servo/heapsize#41]
We can success to compile this on Windows by #40, but it has not implemented to measure on Windows yet.

**Comment by nox** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa366706(v=vs.85).aspx

**Comment by nox** [comment]
That can be closed.

**Comment by saneyuki** [comment]
By #45 ?

**Comment by nox** [comment]
Yes.
