### ISSUE TITLE
Implement heapsize for all the libraries servo uses

### ISSUE THREAD

**Issue by notriddle** [servo/heapsize#5]
These are all the libraries that had HeapSizeOf definitions in `components/util`:

- [x] [azure](https://github.com/servo/rust-azure/pull/193)
- [x] [cssparser](https://github.com/servo/rust-cssparser/pull/85)
- [x] [euclid](https://github.com/servo/euclid/issues/99)
- [ ] [html5ever](https://github.com/servo/html5ever/pull/177)
- [ ] hyper
- [ ] [mime](https://github.com/hyperium/mime.rs/pull/30)
- [ ] layers
- [x] [mozjs](https://github.com/servo/rust-mozjs/pull/187)
- [x] [string_cache](https://github.com/servo/string-cache/pull/105)
- [x] [selectors](https://github.com/servo/rust-selectors/pull/51)
- [x] std
- [x] [url](https://github.com/servo/rust-url/pull/123)
- [ ] util itself (range, cursor, geometry, logical_geomtry)

**Comment by jdm** [comment]
I am keen to am hyper support, too.

**Comment by Manishearth** [comment]
Should we advertise this library as something for the general community to use?

**Comment by SimonSapin** [comment]
@nnethercote suggests moving it into std so that std types can implement it in less hackish ways (e.g. getting a pointer from a private field): https://github.com/servo/heapsize/pull/1#discussion_r36576716

**Comment by Manishearth** [comment]
I'm not sure if that will happen -- even the regex lib (arguably more useful) is not part of std.

Post-MIR we may be able to generalize `derive` so it can be applied to crates preceding the one defining the trait via metadata (not sure if private fields will work).

**Comment by SimonSapin** [comment]
The argument is not that it’s more useful, but that implementing it for `std` types outside of `std` (so without access to private fields) requires [guessing](https://github.com/servo/heapsize/blob/dd121fe093659532e1a121def94bd5f46be41473/src/lib.rs#L144-L145) or [crazy unsafe](https://github.com/servo/heapsize/blob/dd121fe093659532e1a121def94bd5f46be41473/src/lib.rs#L158) code.

**Comment by Manishearth** [comment]
Sure, but that just makes a case for why this should be in std, not for why std would want this :smile:

**Comment by jdm** [comment]
std is the ideal here, but I'd like further experience making use of it in the wider world before committing to the RFC process.
