### ISSUE TITLE
Segfaults in heap_size_of_impl

### ISSUE THREAD

**Issue by rphmeier** [servo/heapsize#82]
Full description here: https://github.com/paritytech/parity/issues/5667

> Hi. I receive a segfault during initial sync. Preconditions:
> 1) Built from commit "99a1636 [ci skip] js-precompiled 20170519-161414". No matter debug or release.
> 2) Rust version: rustc 1.19.0-nightly (e40beb3af 2017-05-11)
> 3) Run on Ubuntu 16.04 x64
> Output:
> ```
> user@Vostro-3750:~/GIT/parity$ ./target/debug/parity 
> 2017-05-20 01:10:57  Starting Parity/v1.7.0-unstable-99a1636-20170519/x86_64-linux-gnu/rustc1.19.0-nightly
> 2017-05-20 01:10:57  State DB configuration: fast
> 2017-05-20 01:10:57  Operating mode: active
> 2017-05-20 01:10:57  Configured for Foundation using Ethash engine
> 2017-05-20 01:10:58  Updated conversion rate to Ξ1 = US$124.84 (953601600 wei/gas)
> 2017-05-20 01:11:00  Removed existing file '/home/user/.local/share/io.parity.ethereum/jsonrpc.ipc'.
> 2017-05-20 01:11:05  Public node URL: enode://1f3b4095eda9852dc0610204ee5a255973dd4c4b5978f38b84f98da9e109a0a086ce02316345229b811680a2439da60d2b6547140c7d33825b094b5b261213c1@192.168.0.104:30303
> 2017-05-20 01:11:05  Syncing #3730000 41f3…bed9     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3730000    0/ 4/25 peers     1 KiB db   10 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
> 2017-05-20 01:11:15  Syncing #3730000 41f3…bed9     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3730000    4/ 4/25 peers     1 KiB db   10 KiB chain  0 bytes queue  858 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
> Segmentation fault (core dumped)
> ```
> Here are the [crashdump](
> https://mega.nz/#!sQkSBCgY!GcW6sMn5W9mWp53KJ4XJxjrxnmsFRQesJGKNt84DPhc
> ) and the [strace](
> https://mega.nz/#!JBFnUJJL!2B-7z8Yop2uKgzIMrQpJ8pnZswWv_cMHU779hPz6ouY
> )

**Comment by jdm** [comment]
Plausibly fixed by #81 already. I've asked for an update in paritytech/parity#5667.

**Comment by rphmeier** [comment]
@jdm, awesome. I'll make a patch and ask the folks there to give it a try.
