### ISSUE TITLE
Nightly allocator API has changed

### ISSUE THREAD

**Issue by jdm** [servo/heapsize#86]
TravisCI is failing on nightly builds because alloc::heap::alloc and alloc::heap::dealloc don't exist any more.

**Comment by SimonSapin** [comment]
The replacement in the `std::heap::Heap` unit struct that implements the `std::heap::Alloc` trait.

**Comment by jdm** [comment]
https://doc.rust-lang.org/nightly/std/heap/struct.Heap.html

**Comment by SimonSapin** [comment]
Fixed in https://github.com/servo/heapsize/pull/90.
