### ISSUE TITLE
`heap_size_of` should be unsafe

### ISSUE THREAD

**Issue by bluss** [servo/heapsize#9]
It draws attention directly by being marked safe but using a raw pointer argument.

It seems trivial to segfault using this function in safe rust, just give it a pointer to something not allocated, or a dangling pointer.

Tested using heapsize 0.1.0

```rust
heapsize::heap_size_of(2 as *const _);
```

**Comment by jdm** [comment]
This is true!

**Comment by nnethercote** [comment]
Is `2 as *const _` itself not unsafe?

**Comment by SimonSapin** [comment]
No, only dereferencing it is.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rfcs/pull/1184#issuecomment-123446297

**Comment by bluss** [comment]
`let v = vec![0; N]; v[1..].as_ptr()` would have the same problem (pointer not from jemalloc).  Creating raw pointers being unsafe or not, the precondition is that the passed in pointer must have been returned from jemalloc, and that is not checkable by the type system.

**Comment by bluss** [comment]
cool :tropical_drink:
