### ISSUE TITLE
`je_malloc_usable_size` vs. `malloc_usable_size` - unknown symbol for macos 

### ISSUE THREAD

**Issue by aarlt** [servo/heapsize#97]
Disclaimer: I'm not a `rust` developer.  

It looks like that https://github.com/servo/heapsize/blob/master/src/lib.rs#L44 seem to create linking problems - at least on macos 10.13.6. It looks like that you rename the symbol to be `je_malloc_usable_size ` for `macos`, `ios` and `android` systems. At least for macos - after installing jemalloc with `brew install jemalloc` - the jemalloc library that will be installed doesn't define a symbol named `je_malloc_usable_size` - but there is a symbol `malloc_usable_size` defined here.

The issue originally came up here: https://github.com/paritytech/parity-ethereum/issues/9167.

**Comment by jdm** [comment]
Maybe the solution here is to add a non-default cargo feature named `unprefixed_malloc` that would inhibit [this line](https://github.com/servo/heapsize/blob/master/src/lib.rs#L44). This would allow projects to override the defaults for whatever configuration they require.

**Comment by aarlt** [comment]
@jdm thank you for your reply
